### PR TITLE
Use more idiomatic C# under the hood

### PR DESCRIPTION
**Pull request by msoucy**
Also makes some small tweaks to the public interface to make things more convenient

### CODE REVIEW

**Review by ThadHouse — CHANGES_REQUESTED** [review]
Can you move the InitDefaultCommand change into a separate PR? That is a slightly major change from upstream WPILib. I would be willing to PR this there, as it is probably a good change, but wouldn't want to merge here until that happens.

**Review by ThadHouse — CHANGES_REQUESTED** [review]
Can you also move the SendableChooser change to a separate PR? Just like the command one, I want to match WPILib. We've actually been talking about major updates to the whole SmartDashboard interface, so that will definitely be a part of those changes.

**Comment by ThadHouse** [comment]
Other than those 2 requested changes, everything else is good. Get those 2 portions into separate PR's and I'll merge the rest of them.

**Comment by msoucy** [comment]
I've removed the "default to no command" commit... which apparently github review didn't appreciate. It's a separate branch, which will be made as a PR soon.

The SendableChooser changes bring it more in line with upstream WPILib - according to wpilibsuite/allwpilib@15e58acc761cf4bf02737f8e014e983d32a739ed it uses a hashmap currently

**Comment by ThadHouse** [comment]
Oh I had forgotten we had actually merged that change. I thought it was still open. My bad.

**Review by ThadHouse — APPROVED** [review]

**Comment by msoucy** [comment]
Is there anything else that needs to be done for this?

**Comment by ThadHouse** [comment]
I'll merge this tonight when I get home. I won't do a release until next weekend. I'm trying to match up with the WPILib release schedule, and I think we are planning on a release this weekend.

**Pull request merged**
