### PR TITLE
Made tests that use System.Reflection.Context and the System.Reflection.Context reference conditionally not compile for the Travis CI build (since Mono doesn't have that assembly).

### PR DESCRIPTION
**Pull request by jkoritzinsky**
This pull request will fix issue #99.  I decided to have the code conditionally compile out instead of removing it because I want to leave possible support in the case that we ever complete #100 (where we will be able to utilize the functionality).

### CODE REVIEW

**Comment by jkoritzinsky** [comment]
The test failure on the pr check is not related to any code from this build... Not quite sure what happened there. @ThadHouse can you take a look?

**Comment by ThadHouse** [comment]
That test fails semi often if the AppVeyor servers are more loaded up. I might just cut it.

Also, if CustomReflectionContext doesn't exist in Mono, how would you actually use the ReflectionContext stuff on the RoboRIO? Is there a way to do so that we know works on the RoboRIO?

EDIT: AHH didnt read the entirety of the PR. Maybe we should comment it out of the current code for now, if there's no way to run it on the RoboRIO. That way it doesn't get accidentally used where it doesnt work.

**Comment by ThadHouse** [comment]
Also maybe we should rename the Travis config to the Mono config. The only reason I found the bug is because someone tried compiling manually on Mono and it didn't work.

**Comment by jkoritzinsky** [comment]
There isn't a way at the moment but it's easier to leave the code in now then remove it and re-add it when Mono support is added. This way the tests make sure that it doesn't break (at least on AppVeyor).

**Comment by jkoritzinsky** [comment]
I can rename it to Mono if you want. I was just naming it similar to the AppVeyor target since it is also used for CI.

**Comment by ThadHouse** [comment]
Ah OK. Should we mark it obsolete and give a decent warning message so nobody attempts to use it. I know thats kind of a backwards way of using obsolete, but unless theres something else it might be the best way. Its gonna be a weird error if somebody tries to load that onto a robot.

**Comment by jkoritzinsky** [comment]
Well the Extras assembly should still build. There's just nothing useful (other than null) that can be passed as a parameter for a ReflectionContext.

**Comment by ThadHouse** [comment]
The only reason for the AppVeyor specific one is to ignore all the compiler warnings. It doesn't actually change any configuration. Release will build properly. However as release won't build properly on mono anyway, it might be worth it to name it Mono.

**Comment by ThadHouse** [comment]
It will build, however if building for the RoboRIO in Visual Studio, adding a custom reflection context would compile correctly. Just when it gets uploaded to the RoboRIO it would crash.

**Comment by jkoritzinsky** [comment]
Oh. Got it. I'll make the change and push it on to this branch in the next few days.

**Comment by jkoritzinsky** [comment]
I have the configuration named MonoDebug now.  Let me know what you think.

**Comment by ThadHouse** [comment]
Looks good other than the Travis configuration either needs to change the test location to bin/MonoDebug, or switch the MonoDebug configuration back to Output\ Other then that should be good.

**Comment by msoucy** [comment]
Is there a way to get this completed? It would be nice to have on the mainline

**Comment by jkoritzinsky** [comment]
Sorry for the delay. I'll merge this in as soon as the CI build confirms that I haven't broken anything.

**Pull request merged**
