### PR TITLE
Vs2017

### PR DESCRIPTION
**Pull request by ThadHouse**

### CODE REVIEW

**Comment by msoucy** [comment]
Is there anything that can be done to help get this ready and integrated in the main codebase? Alternatively, will this be retargeted for .NET Core 2.0?

**Comment by ThadHouse** [comment]
I just haven't had time to work on this at all this summer. I probably won't have time to finish it before the season starts either. However, if someone is willing to start from this, I'd be perfectly happy to accept a PR. If not, I'll just rebuild all the current sources for the new season. 

.Net Core 2.0 is fine with me, as I will be building mono 5.2 for the new season. If possible still keep around the 4.5.2 build, but with net core 2.0 they should be the same compile.

**Comment by ThadHouse** [comment]
I'd rather spend my dev time getting the updated deployment working, as that's the harder side to figure out, and this can all be done independently. I hope to have a vs 2017 and cli plugin for the season, and that is higher on the priority list. In addition to rebuilding networktables, since the ntcore API changed, and old binaries don't work anymore.

**Comment by ThadHouse** [comment]
I don't think I'm going to end up having time to fully implement this this season. I've been swamped with school, work, and getting everything else working in upstream wpilib. My plan will just be to have the same functionality as last year working, but upgraded to the 2018 image. If somebody else want to take over and get this upgraded to .NET Standard I'd be happy to have that happen, I just don't think I'll have time before the season starts to finish all of this. Also, because of some other issues, I'm happy to drop the .NET framework builds, and only build a .NET standard build if somebody wants to build that.

**Comment by msoucy** [comment]
What does this mean for the VS 2017 plugin and CLI?

**Comment by ThadHouse** [comment]
I'll merge the PR that is in the current plugin repo that enables it to work in 2017. I don't think I'll keep working on the CLI until we can run .NET Core on the roborio. There were some issues with the CLI on linux when trying to build a framework project that still haven't been fixed yet. So for now its not worth the engineering time to completely rebuild the plugins when the API might change once the linux issues get fixed. If someone else wants to continue work on those and think they can get something working before the season that is fine with me, but I just won't have the time to guarantee that it gets finished by the start of the season.

**Comment by ThadHouse** [comment]
This is very much OBE by 2021 being a restart from the very beginning.

**Pull request closed without merging**
